# Generated by Django 2.0 on 2017-09-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=64)),
                ('type1', models.CharField(max_length=64)),
            ],
        ),
    ]
