# Generated by Django 2.0 on 2017-09-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('jjjz', models.FloatField()),
                ('ljjz', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
