# Generated by Django 2.0 on 2017-10-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_fundvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundValueCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('increases', models.FloatField()),
                ('jitter', models.FloatField()),
            ],
        ),
    ]
