# Generated by Django 2.0 on 2017-10-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_fundvaluecalc'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundvaluecalc',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
