# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-24 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0006_fundmanager_fundtomanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundmanager',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundmanager',
            name='desc',
            field=models.TextField(),
        ),
    ]
