# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-25 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0007_auto_20180224_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('record_time', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
    ]
