# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-25 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0008_devinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundValueDeal1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_incr', models.FloatField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.FundInfo')),
            ],
        ),
    ]
