# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-25 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0009_fundvaluedeal1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundvaluedeal1',
            old_name='month_incr',
            new_name='month_income',
        ),
    ]
