# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-25 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0010_auto_20180225_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundvaluedeal1',
            name='update_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
